module.exports = function() {
  return {
    clientAllowedKeys: ['SITE_TITLE',
                        'NAVMENU_TITLE',
                        'SEARCH_URL',
                        'ORCID_URL',
                        'FABRICA_URL',
                        'API_URL',
                        'EVENTDATA_URL',
                        'CDN_URL',
                        'JWT_PUBLIC_KEY',
                        'USER_NAME',
                        'SENTRY_DSN',
                        'AWS_ACCESS_KEY',
                        'AWS_SECRET_KEY',
                        'AWS_BUCKET',
                        'AWS_REGION'],
    fastbootAllowedKeys: ['SITE_TITLE',
                        'NAVMENU_TITLE',
                        'SEARCH_URL',
                        'ORCID_URL',
                        'FABRICA_URL',
                        'API_URL',
                        'EVENTDATA_URL',
                        'CDN_URL',
                        'JWT_PUBLIC_KEY',
                        'USER_NAME',
                        'SENTRY_DSN',
                        'AWS_ACCESS_KEY',
                        'AWS_SECRET_KEY',
                        'AWS_BUCKET',
                        'AWS_REGION'],
    failOnMissingKey: false, 
  };
};
