name: Build
on:
  workflow_call:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        id: cypress-cache
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            node_modules
            ~/.cache/Cypress
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Get branch name
        run: |
          echo "### CURRENT BRANCH NAME:  ${{ github.ref_name }}."

      - name: Build
        run: |
          yarn --prefer-offline
          ./node_modules/.bin/ember build --output-path="test_build" --environment=development

      - name: Upload Test Build artifact
        uses: actions/upload-artifact@v4
        with:
          name: test_build
          path: test_build/
