name: Ember Tests
on:
  workflow_call:   
jobs:
  ember-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        id: cypress-cache
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            node_modules
            ~/.cache/Cypress
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Download Test Build artifact
        uses: actions/download-artifact@v4
        with:
          name: test_build
          path: test_build/

      - name: Ember Testing
        env:
          COVERAGE: true
        run: |
          yarn run ember test --path=test_build
